[package]
name = "tiny-db"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
moka = { version = "0.12", features = ["sync"] }
serde = { version = "1", features = ["derive"] }
rmp-serde = "1"
tokio = { version = "1", features = ["fs", "io-util", "macros", "rt-multi-thread"]}